name: Lootin
version: ${project.version}
main: com.github.sachin.lootin.Lootin
api-version: 1.16
authors: [ sachingorkar ]
softdepend: [PlaceholderAPI,ProtocolLib,WorldGuard,YskLib]
description: Loot per player
api: []
folia-supported: true


permissions:
  lootin.breakchest.bypass:
    default: op
  lootin.breakelytraitemframe.bypass:
    default: op
  lootin.preventfilling.bypass:
    default: op
  lootin.autoreplenish:
    default: true
  lootin.command.*:
    default: op
    children:
      lootin.command.reload: true
      lootin.command.rwggive: true
      lootin.command.set: true
      lootin.command.info: true
      lootin.command.clear: true
      lootin.command.test: true
      lootin.command.refill: true
      lootin.command.generatetables: true
      lootin.command.reloadtables: true
      lootin.command.listitemedit: true
      lootin.command.resetvault: true
      lootin.command.vaultinfo: true